.TH MYSTRLEN 3 "September 21, 2025" "libmyutils 0.4.1" "Library Functions"
.SH NAME
mystrlen \- return length of a null-terminated string
.SH SYNOPSIS
.B int mystrlen(const char *s);
.SH DESCRIPTION
Returns the number of characters in the string argument before the terminating NUL byte.
.SH RETURN VALUE
Length of the string as an integer.
.SH AUTHOR
Khansa Azeem <your_email@example.com>
