.TH WORDCOUNT 3 "September 21, 2025" "libmyutils 0.4.1" "Library Functions"
.SH NAME
wordCount \- count lines, words and characters in a file stream
.SH SYNOPSIS
.B int wordCount(FILE *file, int *lines, int *words, int *chars);
.SH DESCRIPTION
Counts the number of lines, words and characters from the provided file stream.
Returns 0 on success and -1 on error.
.SH AUTHOR
Khansa Azeem <your_email@example.com>
